# Generated by Django 5.0.2 on 2024-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='place',
            field=models.CharField(default='', max_length=150),
        ),
    ]
